export const PERMISSIONS_KEY = {
  ROLE_READ: 'read:role',
  ROLE_CREATE: 'create:role',
  ROLE_UPDATE: 'update:role',
  ROLE_DELETE: 'delete:role',
  PERMISSION_READ: 'read:permission',
  PERMISSION_CREATE: 'create:permission',
  PERMISSION_UPDATE: 'update:permission',
  PERMISSION_DELETE: 'delete:permission',
  PERMISSION_ASSIGN_ROLE: 'assign:permission:role',
  PERMISSION_REMOVE_ROLE: 'remove:permission:role',
  USER_CREATE: 'create:user',
  USER_READ: 'read:user',
  USER_UPDATE: 'update:user',
  USER_DELETE: 'delete:user',
  USER_MANAGE: 'manage:user',
  COMPANY_CREATE: 'create:company',
  COMPANY_READ: 'read:company',
  COMPANY_UPDATE: 'update:company',
  COMPANY_DELETE: 'delete:company',
  COMPANY_MANAGE: 'manage:company',
  ALL_MANAGE: 'manage:all',
  ADMIN_READ: 'read:admin',
  ADMIN_CREATE: 'create:admin',
  ADMIN_UPDATE: 'update:admin',
  ADMIN_DELETE: 'delete:admin',
};
